apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  labels:
    app: javawebapp
spec:
  containers:
    - name: javawebappcontainer
      image: ashokit/javawebapp
      ports:
        - containerPort: 8080
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: javawebappservice
#spec:
#  type: ClusterIP
#  selector:
#    app: javawebapp
#  ports:
#    - port: 80
#      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappservice
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080