apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxsvc
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: nginxpod
      labels:
        app: nginxapp
    spec:
      containers:
        - name: nginxcontainer
          image: nginx
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  type: NodePort
  selector:
    app: nginxapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002

